FROM php:7.1-fpm

RUN apt-get update && apt-get install -y libmcrypt-dev default-mysql-client \
    && docker-php-ext-install mcrypt pdo_mysql bcmath && \

    #zip,unzip
    apt-get install -y zip unzip && \

    #vim
    apt-get install -y vim && \

    # node, npm
    apt install -y nodejs npm && \

    # node, npmを最新のバージョンにする
    npm install n -g && \
    n stable && \
    apt purge -y nodejs npm && \

    #composer
    curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer && \

    #user追加
    useradd -m -s /bin/bash -u 1000 dev && \

    #www.conf修正
    sed -i 's/user\ \=\ www-data/user\ \=\ dev/g' /usr/local/etc/php-fpm.d/www.conf && \
    sed -i 's/group\ \=\ www-data/group\ \=\ dev/g' /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www
